export const routes = {
  home: "/",
  following: "/following",
  profile: "/@:nickname",
  editprofile: "/@:nickname/edit",
  profileLink: (nickname) => `/@${nickname}`,
  editProfileLink: (nickname) => `/@${nickname}/edit`,
  live: "/live",
  upload: "/upload",
  search: "/search",
  messages: "/messages",
  notification: "/notification",
  login: "/login",
  register: "/register",
  video: "/@:nickname/videos/:id",
  // videoLink: (content) => `/${content.file_url}`,
  videoLink: (content) => `/@${content.user.nickname}/videos/${content._id}`,
  comment: "/videos/:id/comments",
};
