export const routes = {
  home: "/",
  following: "/following",
  profile: "/@:nickname",
  booth: "/@:nickname/booth",
  editprofile: "/@:nickname/edit",
  editproduct: "/@:id/edit_product",
  addProduct: "/@:nickname/add_product",
  profileLink: (nickname) => `/@${nickname}`,
  boothLink: (nickname) => `/@${nickname}/booth`,
  editProfileLink: (nickname) => `/@${nickname}/edit`,
  editProductLink: (product) => `/@${product._id}/edit_product`,
  addProductLink: (nickname) => `/@${nickname}/add_product`,
  live: "/live",
  upload: "/upload",
  search: "/search",
  messages: "/messages",
  cart: "/cart",
  notification: "/notification",
  login: "/login",
  register: "/register",
  video: "/@:nickname/videos/:id",
  // videoLink: (content) => `/${content.file_url}`,
  videoLink: (content) => `/@${content.user.nickname}/videos/${content._id}`,
  videoLinknoti: (content) => `/videos/${content}`,
  comment: "/videos/:id/comments",
};
